name: tests

on:
  push:
  pull_request:

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4, 8.0]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Prepare the environment
        run: cp .env.example .env

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --ignore-platform-reqs --optimize-autoloader

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests (Unit and Feature)
        run: vendor/bin/phpunit
